<?php
/*
* This file was automatically generated by Path
* Modify to suit your usage
* 
*/
namespace Path\App\Http\MiddleWares;


use Path\Core\Http\MiddleWare;
use Path\Core\Http\Request;
use Path\Core\Http\Response;

class ValidatePassword implements MiddleWare
{
    private $password = "<adewale96/>";
    /**
     * @param Request $request
     * @param Response $response
     * @return mixed
     * @internal param $params
     */
    public function validate(Request $request, Response $response):bool
    {
        return $request->fetch("password") && $request->fetch("password") === $this->password;
    }

    public function fallBack(Request $request, Response $response)
    {
            return $response->json(["middleware_msg" => "Invalid password "],401);
    }
}
