<?php
/*
* This FIle was automatically generated By Path
* Modify to your advantage
*/

namespace Path\App\Database\Migration;


use Path\Core\Database\Model;
use Path\Core\Database\Prototype;
use Path\Core\Database\Structure;
use Path\Core\Database\Table;


class BlogPosts implements Table
{
    public $table_name = "blog_posts";
    public $primary_key = "id";
    public function install(Structure &$table)
    {
        $table->column("title")
            ->type("TEXT")
            ->nullable();

        $table->column("body")
            ->type("TEXT")
            ->nullable();

        $table->column("author")
            ->type("TEXT")
            ->nullable();

    }

    public function uninstall()
    {
    }

    public function populate(Model $table)
    {

        $table->insert([
            "title" => "Hello world, This is your First Post",
            "body"  => "You Can delete this Post and Others  In [/manage/list/posts](/manage/list/posts), check `path/Http/MiddleWares/ValidatePassword.php` to see authentication password",
            "author"=> "Sulaiman Adewale"
        ]);


    }

    public function update(Structure &$table)
    {
    }
}