<?php
/*
* This Live Controller File Was automatically 
* Generated by Path
* Modify to Suite your needs,
* */

namespace Path\Controller\Live;

use Path\Core\Http\Watcher\WatcherInterface;
use Path\Core\Storage\Caches;
use Path\Core\Http\Response;
use Path\Core\Http\Watcher;
use Path\Core\Router\Live\Controller;
use Path\Database\Models\Blog;
use Path\Core\Storage\Sessions;

import(
    "core/classes/Database/Model",
    "path/Database/Models/Blog"
);

class LiveBlog extends Controller
{
     
    public $blogs;

    public function onConnect(
        WatcherInterface &$watcher,
        Sessions $sessions
    )
    {
        parent::onConnect($watcher, $sessions); // TODO: Change the autogenerated stub
    }


}
        